In [1]:
import numpy as np

In [3]:
np.random.rand(6,3)

array([[0.62331841, 0.3081471 , 0.40910745],
       [0.24508778, 0.3763761 , 0.5096115 ],
       [0.3770657 , 0.9538677 , 0.58079776],
       [0.27651431, 0.45711236, 0.83556583],
       [0.15126425, 0.05693849, 0.48203974],
       [0.16706977, 0.58756404, 0.55314266]])

In [5]:
x=np.zeros((6,6))

In [8]:
x[:,0:3]=np.random.rand(6,3)

In [9]:
x

array([[0.74059284, 0.83263245, 0.76363396, 0.        , 0.        ,
        0.        ],
       [0.3943478 , 0.32458891, 0.98127706, 0.        , 0.        ,
        0.        ],
       [0.76669476, 0.90497832, 0.44635235, 0.        , 0.        ,
        0.        ],
       [0.18883559, 0.69064628, 0.43647918, 0.        , 0.        ,
        0.        ],
       [0.59345561, 0.01452244, 0.45776702, 0.        , 0.        ,
        0.        ],
       [0.84962846, 0.32658764, 0.21673816, 0.        , 0.        ,
        0.        ]])

In [10]:
x[0:3,3:6]=-1*np.identity(3)

In [11]:
x

array([[ 0.74059284,  0.83263245,  0.76363396, -1.        , -0.        ,
        -0.        ],
       [ 0.3943478 ,  0.32458891,  0.98127706, -0.        , -1.        ,
        -0.        ],
       [ 0.76669476,  0.90497832,  0.44635235, -0.        , -0.        ,
        -1.        ],
       [ 0.18883559,  0.69064628,  0.43647918,  0.        ,  0.        ,
         0.        ],
       [ 0.59345561,  0.01452244,  0.45776702,  0.        ,  0.        ,
         0.        ],
       [ 0.84962846,  0.32658764,  0.21673816,  0.        ,  0.        ,
         0.        ]])

In [20]:
b=np.zeros((6,1))

In [21]:
b[4,:]=1

In [22]:
b

array([[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.]])

In [23]:
np.linalg.solve(x,b)

array([[-0.03086475],
       [-1.42602573],
       [ 2.26977083],
       [ 0.52306057],
       [ 1.75223048],
       [-0.30106866]])