In [1]:
import numpy as np


In [2]:
n=10


In [34]:
S=np.random.rand(n,n)

S=S+S.T

In [35]:
S

array([[0.31839406, 0.40586941, 1.11086501, 0.60381831, 1.43437995,
        0.66366001, 0.79498806, 0.71151562, 1.31545925, 0.46523256],
       [0.40586941, 1.03490665, 1.46430922, 0.6734346 , 1.09803363,
        1.50767168, 1.03104378, 1.29348053, 0.94035485, 1.00956588],
       [1.11086501, 1.46430922, 1.97205225, 0.48185859, 1.37963065,
        0.50798854, 0.81594635, 1.13410753, 0.65745679, 1.23384919],
       [0.60381831, 0.6734346 , 0.48185859, 1.80716195, 0.98413985,
        0.70572146, 0.29308488, 1.37834525, 1.65528491, 1.77304556],
       [1.43437995, 1.09803363, 1.37963065, 0.98413985, 1.14537756,
        1.45371535, 1.10449421, 0.75322182, 0.78949885, 1.17713026],
       [0.66366001, 1.50767168, 0.50798854, 0.70572146, 1.45371535,
        0.40568454, 0.55528321, 1.42033994, 1.59800011, 1.77295713],
       [0.79498806, 1.03104378, 0.81594635, 0.29308488, 1.10449421,
        0.55528321, 0.17575853, 1.33743723, 1.80347018, 0.90460015],
       [0.71151562, 1.29348053, 1.1341075

In [36]:
B=np.random.rand(n,n)
B

array([[0.65276241, 0.4360364 , 0.73394469, 0.82789801, 0.39443239,
        0.89706436, 0.15877874, 0.97968473, 0.8499663 , 0.93677717],
       [0.93685884, 0.91662492, 0.27682496, 0.68107713, 0.15435118,
        0.73864564, 0.58768238, 0.54349669, 0.71998753, 0.53202642],
       [0.6467894 , 0.84223156, 0.57551942, 0.15698113, 0.52484373,
        0.64997396, 0.16305655, 0.97382857, 0.6118062 , 0.20700583],
       [0.00413629, 0.94261705, 0.3307082 , 0.85555861, 0.71094035,
        0.63842396, 0.62359223, 0.61929071, 0.94172692, 0.84807982],
       [0.26102986, 0.98352532, 0.37835788, 0.74102004, 0.74381044,
        0.04233501, 0.49770572, 0.60783663, 0.79682542, 0.3931989 ],
       [0.9663983 , 0.99222482, 0.28192469, 0.92126768, 0.08648228,
        0.70455219, 0.24701179, 0.20571306, 0.2577953 , 0.4659064 ],
       [0.93984326, 0.93021408, 0.89465657, 0.28384479, 0.9756638 ,
        0.78159975, 0.80334911, 0.03523938, 0.52091254, 0.97528615],
       [0.64157182, 0.07305562, 0.5939417

In [37]:
C=np.zeros(shape=(n,n))
np.fill_diagonal(C,np.random.rand(n))

In [38]:
C

array([[0.49238245, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.95642075, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.64007739, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.79025381, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.34555754,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.1717794 , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.93083537, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.       

In [39]:
np.fill_diagonal(B,B.diagonal()-B.sum(axis=1)-np.random.rand(n))
B

array([[-6.62408998e+00,  4.36036401e-01,  7.33944694e-01,
         8.27898009e-01,  3.94432386e-01,  8.97064360e-01,
         1.58778743e-01,  9.79684728e-01,  8.49966304e-01,
         9.36777170e-01],
       [ 9.36858843e-01, -6.07462226e+00,  2.76824956e-01,
         6.81077127e-01,  1.54351178e-01,  7.38645635e-01,
         5.87682379e-01,  5.43496686e-01,  7.19987527e-01,
         5.32026416e-01],
       [ 6.46789401e-01,  8.42231564e-01, -5.47615731e+00,
         1.56981130e-01,  5.24843725e-01,  6.49973965e-01,
         1.63056554e-01,  9.73828572e-01,  6.11806198e-01,
         2.07005831e-01],
       [ 4.13628835e-03,  9.42617048e-01,  3.30708197e-01,
        -5.94289763e+00,  7.10940352e-01,  6.38423955e-01,
         6.23592230e-01,  6.19290706e-01,  9.41726918e-01,
         8.48079822e-01],
       [ 2.61029857e-01,  9.83525323e-01,  3.78357881e-01,
         7.41020040e-01, -5.51476537e+00,  4.23350087e-02,
         4.97705720e-01,  6.07836626e-01,  7.96825420e-01,
         3.

In [40]:
((B@S+S@B.T+C)**2).sum()

2435.1583033307893

In [149]:
for i in range(30):
    B-=0.001*(2*(B@S+S@B.T)+C.T+C)@S
    C-=0.001*2*(B@S+S@B.T+C)
    C=C*np.identity(n)
    print(((B@S+S@B.T+C)**2).sum())

0.08039794217721263
0.0802051030996333
0.08001273071773925
0.0798208238872181
0.07962938146698874
0.07943840231848215
0.07924788530611845
0.07905782929716125
0.07886823316166942
0.07867909577254696
0.07849041600546612
0.07830219273898466
0.07811442485436564
0.07792711123578873
0.07774025077005066
0.07755384234690364
0.07736788485879047
0.07718237720085076
0.07699731827110186
0.07681270697024582
0.07662854220174983
0.07644482287180768
0.07626154788931361
0.07607871616596328
0.07589632661608568
0.07571437815676794
0.07553286970778517
0.07535180019158433
0.07517116853333011
0.07499097366086795


In [65]:
B@S+S@B.T

array([[-0.10826903,  1.61568434, -0.03776282,  0.02815453, -1.4948052 ,
         0.70646024, -1.31394659,  0.82473102, -0.48753211, -0.07803   ],
       [ 1.61568434,  0.1321332 , -0.16062109,  1.5500417 ,  0.38913371,
        -1.58478323, -0.05622161, -1.01341647,  0.66318415, -2.02743327],
       [-0.03776282, -0.16062109, -1.28966004, -1.19619208,  0.4996762 ,
         1.61321507, -0.35035475, -0.59782909,  0.29181056,  0.50704207],
       [ 0.02815453,  1.5500417 , -1.19619208, -1.04588953,  0.06297945,
         0.19645406,  0.67815897,  0.05633633,  0.16914429, -0.83552846],
       [-1.4948052 ,  0.38913371,  0.4996762 ,  0.06297945, -2.02280552,
        -1.18338299,  1.36820487,  1.11057949, -0.18576962, -0.04331215],
       [ 0.70646024, -1.58478323,  1.61321507,  0.19645406, -1.18338299,
         0.77052508, -0.61524493,  0.13431858,  0.88812745,  0.16076729],
       [-1.31394659, -0.05622161, -0.35035475,  0.67815897,  1.36820487,
        -0.61524493,  1.48381045, -0.21906833

In [52]:
C

array([[-0.65869627,  0.22732729,  0.62911356, -0.11984242,  0.70122042],
       [ 0.22732729, -0.88616492,  0.54855482,  0.37452672, -0.04319219],
       [ 0.62911356,  0.54855482, -0.8761891 , -0.13423399,  0.63980978],
       [-0.11984242,  0.37452672, -0.13423399,  1.27299447, -0.94439598],
       [ 0.70122042, -0.04319219,  0.63980978, -0.94439598, -0.35178021]])

In [259]:
B@S+S@B.T+C

array([[ 0.00579819, -0.01383062, -0.01354303,  0.00462458,  0.01685253],
       [-0.01383062,  0.03299064,  0.03230466, -0.01103117, -0.04019892],
       [-0.01354303,  0.03230466,  0.03163295, -0.0108018 , -0.03936306],
       [ 0.00462458, -0.01103117, -0.0108018 ,  0.00368853,  0.01344143],
       [ 0.01685253, -0.04019892, -0.03936306,  0.01344143,  0.04898218]])

In [55]:
C*np.identity(n)

array([[-0.65869627,  0.        ,  0.        , -0.        ,  0.        ],
       [ 0.        , -0.88616492,  0.        ,  0.        , -0.        ],
       [ 0.        ,  0.        , -0.8761891 , -0.        ,  0.        ],
       [-0.        ,  0.        , -0.        ,  1.27299447, -0.        ],
       [ 0.        , -0.        ,  0.        , -0.        , -0.35178021]])